mysql:
  datasource:
    order:
      url: jdbc:mysql://139.155.73.132:3306/order
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      mborrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
    points:
      url: jdbc:mysql://139.155.73.132:3306/points
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      mborrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60