server:
  tomcat:
    uri-encoding: UTF-8
    #最小线程数
    min-spare: 50
    #最大线程数
    max: 1000
    #最大链接数
    max-connections: 6500
    #最大等待队列长度
    accept-count: 1000
    #请求头最大长度kb
    max-http-header-size: 1048576
    #请请求体最大长度kb
    #max-http-post-size: 2097152