spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    password: 654321
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
